# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
name: $(SourceBranchName)-PR-$(Date:yyyy-MM-dd)$(Rev:.r)

trigger: none
pr:
  branches:
    include:
    - '*'

resources:
  repositories:
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/heads/main

variables:
  - group: OData-ESRP-CodeSigning

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: MSSecurity-1ES-Build-Agents-Pool
      image: MSSecurity-1ES-Windows-2019
      os: windows
    sdl:
      sourceAnalysisPool:
        name: MSSecurity-1ES-Build-Agents-Pool
        image: MSSecurity-1ES-Windows-2019
        os: windows
      credscan:
        suppressionsFile: $(Build.SourcesDirectory)\.config\CredScanSuppressions.json
        outputFormat: pre
        debugMode: false
        batchSize: 16
      psscriptanalyzer:
        break: false
        enabled: true
    stages:
    - stage: Build
      jobs:
      - job: EntraPowerShellPRBuild
        displayName: Entra PowerShell PR Build
        steps:
          - template: .azure-pipelines/generation-templates/generate_adapter-1es.yml@self
            parameters:
              Sign: false
              